### ISSUE TITLE
Mixed-in "flow layout" sections?

### ISSUE THREAD

**Issue by snoozemoose** [joelekstrom/JEKScrollableSectionCollectionViewLayout#15] opened 2019-11-12 09:57 UTC
Hi!

Thanks for a really great layout project! Would it be possible to add support for having some sections that use "traditional flow layout"? The purpose would be to have some rows/sections scrolling horizontally as today and some sections laid out in a vertically scrolled grid-ish manner.

**Comment by joelekstrom** [comment] 2019-11-12 12:24
Hi! That would be entirely possible, and probably not very hard (actually, an earlier version of the project did have support for this but removed it during a major refactor).

Here's how one can solve that:
- Add a delegate method that asks the delegate if a section should be scrollable or not
- Change the `prepareLayout` function of `JEKScrollableSectionInfo` to not overflow `self.collectionViewWidth` when setting up the frames. It should just be a couple of lines to change.

I'd love to see a PR for this, since I don't know when I'll have time to spend on adding to this project. If you need it soon, please give it a try!

**Comment by snoozemoose** [comment] 2019-11-12 14:25
Thanks for a quick reply! I'm almost done with a working solution thanks to you info. The issue I have now is that the "flow layout" section still can be scrolled horizontally, do you have any pointer to where I should look to fix this?

**Comment by snoozemoose** [comment] 2019-11-12 14:32
And, if you have any ideas as to why the scroll position of the horizontally scrolled rows seem to lose their position after scrolling far down and then back up again I'd be really happy to look into that too. The layout is not re-calculated at any point so I'm a little lost of where to start looking.

**Comment by joelekstrom** [comment] 2019-11-12 15:01
Hmm, that sounds like another issue, it shouldn't be happening 🤔 that would be the `offsetCache`  that is somehow reset. Can happen if sections change their index but doesn't sound like that's a problem according to what you're describing. If it's possible to reproduce in a sample project I could take a look at it

**Comment by snoozemoose** [comment] 2019-11-12 15:10
It must have been related to the scroll configuration that I just added because now when I've prevented the "flow layed" section from horisontal scrolling the issue seems to have gone away. I'll clean things up a bit and submit a PR before end of the day. If I also have time I'll create a reproducible test scenario. 
Oh, and... Don't spare any criticism you might have on the PR, it's been a few years since I used ObjC (only working in Swift now). And of course, if you don't like how I structured the code just let me know and I'll fix it as you want it (I sort of rushed through the changes today).

**Comment by snoozemoose** [comment] 2019-11-12 15:38
PR #16 now submitted

**Comment by joelekstrom** [comment] 2019-11-12 18:07
Cool! Thank you, I’ll take a look at it tomorrow morning 😊

**Comment by joelekstrom** [comment] 2019-11-13 16:22
Released with v1.3.0. Thanks for the help again!

Will push it to cocoapods after some more testing.

**Closed by joelekstrom** 2019-11-13 16:22 UTC

**Comment by snoozemoose** [comment] 2019-11-13 18:53
Awesome! Glad I could make a small contribution 😊!
